PREFIX : <http://purl.bdrc.io/ontology/core/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX adm:   <http://purl.bdrc.io/ontology/admin/>

SELECT ?property ?value
WHERE {
  {
     ?a adm:adminAbout ?m  .
     ?a adm:status ?value .
     BIND ("status" AS ?property)
  } UNION {
     ?b rdf:type :PersonEventBirth .
     ?b :onYear ?value .
     BIND ("birth" AS ?property)
  } UNION {
     ?b rdf:type :PersonEventDeath .
     ?b :onYear ?value .
     BIND ("death" AS ?property)
  } UNION {
     ?m skos:prefLabel ?value .
     BIND ("name[]" AS ?property)
     FILTER (lang(?value) = "bo" || lang(?value) = "bo-x-ewts" || lang(?value) = "sa-x-ewts")
  } UNION {
     ?m :personName/rdfs:label ?value .
     BIND ("name[]" AS ?property)
     FILTER (lang(?value) = "bo" || lang(?value) = "bo-x-ewts" || lang(?value) = "sa-x-ewts")
  }
}
