PREFIX : <http://purl.bdrc.io/ontology/core/>
PREFIX adm: <http://purl.bdrc.io/ontology/admin/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT ?property ?value ?name ?title ?endsAt ?beginsAt ?endsAtVolume ?beginsAtVolume ?nodeRID ?prefLabel
WHERE {
  {
     ?w :workCreator ?value .
     BIND ("creator[URI]" AS ?property)
  } UNION {
     ?w :workPublisherName ?value .
     BIND ("publisherName" AS ?property)
  } UNION {
     ?w :workPublisherDate ?value .
     BIND ("publisherDate" AS ?property)
  } UNION {
     ?w :workPublisherLocation ?value .
     BIND ("publisherLocation" AS ?property)
  } UNION {
     ?w :workPrintType ?value .
     BIND ("printTypeURI" AS ?property)
  } UNION {
     ?b rdf:type :PersonEventBirth .
     ?b :onOrAbout ?value .
     BIND ("birth" AS ?property)
  } UNION {
     ?w adm:workLegacyNode ?nodeRID .
     ?w rdf:type :Work .
     OPTIONAL { ?w :workPartLabel ?name } .
     OPTIONAL { ?w :workTitle/rdfs:label ?title } .
     OPTIONAL { ?w :workLocation/:workLocationEndVolume ?endsAtVolume } .
     OPTIONAL { ?w :workLocation/:workLocationPage ?beginsAt } .
     OPTIONAL { ?w :workLocation/:workLocationEndPage ?endsAt } .
     OPTIONAL { ?w :workLocation/:workLocationVolume ?beginsAtVolume } .
     BIND ("node[]" AS ?property)
     FILTER ((!bound(?name) || lang(?name) = "bo" || lang(?name) = "bo-x-ewts")
             && (!bound(?title) || lang(?title) = "bo" || lang(?title) = "bo-x-ewts"))
  } UNION {
     ?w :workTitle/rdfs:label ?value .
     BIND ("title[]" AS ?property)
     FILTER NOT EXISTS {?w adm:workLegacyNode ?nodeRID } .
     FILTER (NOT EXISTS {} && (lang(?value) = "bo" || lang(?value) = "bo-x-ewts"))
  }
}
